import polyfills from './polyfills';
import './lazyload';
import detectTouch from './detectTouch';
import setScrollbarWidth from './setScrollbarWidth';
import validation from './validation';
import customSelects from './customSelects';
import phoneMask from './phoneMask';
import onlyNumeric from './onlyNumeric';
import fileUpload from './fileUpload';

import introNewsTabs from './introNewsTabs';
import successStories from './successStories';
import hoop from './hoop';
import menu from './menu';
import FixedFooter from './fixedFooter';

import solutionsIntroSlider from './solutionsIntroSlider';
import solutionHoops from './solutionsHoops';
import intro from './intro';
import solutionAccordions from './solutionAccorions';
import solutionExamples from './solutionExamples';
import solutionGallerySlider from './solutionGallerySlider';
import modals from './modals';
import datepicker from './datepicker';
import otherNewsSlider from './otherNewsSlider';
import publicationsSlider from './publicationsSlider';
import articleGallery from './articleGallery';
import pressCenterSlider from './pressCenterSlider';
import ourClientsSlider from './ourClientsSlider';
import anchorLinks from './anchorLinks';
import accordions from './accordions';
import careerCatalogFilter from './careerCatalogFilter';
import partnersSlider from './partnersSlider';
import playersSlider from './playersSlider';
import eventCountdown from './eventCountdown';
import speakers from './speakers';
import whyIteko from './whyIteko';
import solutionHistoryIteko from './solutionHistoryIteko';
import introBlock2 from './introBlock2';

document.addEventListener('DOMContentLoaded', function() {
    polyfills();
    detectTouch();
    setScrollbarWidth();
    validation();
    customSelects();
    phoneMask();
    onlyNumeric();
    fileUpload();
    introNewsTabs();
    successStories();
    hoop();
    menu();
    solutionsIntroSlider();
    solutionHoops();
    intro();
    solutionAccordions();
    solutionExamples();
    solutionGallerySlider();
    FixedFooter();
    modals();
    datepicker();
    otherNewsSlider();
    publicationsSlider();
    articleGallery();
    pressCenterSlider();
    ourClientsSlider();
    anchorLinks();
    accordions();
    careerCatalogFilter();
    partnersSlider();
    playersSlider();
    eventCountdown();
    speakers();
    introBlock2();
});

window.addEventListener('load', function() {
    document.body.classList.add('loaded');
    setTimeout(() => document.body.classList.add('animatable'), 300);
    whyIteko();
    solutionHistoryIteko();
});
